cleanup

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -8,11 +8,12 @@ inputs:
     description: 'the CVMFS sub-directory to place/remove images'
     required: true
   docker_tags:
-    description: 'the list of Docker image tags requested to be built on CVMFS'
+    description: 'the list of Docker image tags requested to be built on CVMFS'  # use `${{ needs.docker.outputs.tags }}`
+    type: string
     default: ''
   include_docker_repo:
-    description: 'whether to include the docker repo when inserting into CVMFS dir'
-    type: boolean
+    description: 'whether to include the docker repo when inserting into CVMFS dir; e.g. icecube/skymap_scanner:3 -> DEST_DIR/skymap_scanner:3 OR DEST_DIR/icecube/skymap_scanner:3'
+    type: boolean  # the incoming type is boolean, but to access it's a string; e.i. 'true', 'false'
     default: 'true'
   delete_image_tags:
     description: 'DELETION MODE: Image tag to match (full tag or prefix for SHA matching)'
@@ -24,11 +25,13 @@ runs:
     - name: Check Inputs
       run: |
         set -euo pipefail
+        # DELETION MODE
         if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
           if [[ -z "${{ inputs.dest_dir }}" || -n "${{ inputs.docker_tags }}" ]]; then
             echo "::error::Input Error: 'delete_image_tags' requires 'dest_dir' and forbids 'docker_tags'."
             exit 1
           fi
+        # CREATION MODE
         elif [[ -z "${{ inputs.docker_tags }}" ]]; then
           echo "::error::Input Error: 'docker_tags' is required for build mode."
           exit 1
@@ -37,19 +40,44 @@ runs:
 
     - uses: actions/setup-python@v4
       with:
-        python-version: '3.11'
+        python-version: '3.13'  # NOTE: update, someday
 
     - name: Checkout WIPACrepo/cvmfs-actions
       uses: actions/checkout@v3
       with:
         repository: WIPACrepo/cvmfs-actions
-        token: ${{ inputs.github_token }}
+        token: ${{ inputs.github_token }}  # so job can git push
 
     - name: Git config
       run: |
         set -euo pipefail
         git config user.name github-actions
         git config user.email github-actions@github.com
+      shell: bash
+
+    - name: Request Build(s) on CVMFS
+      if: inputs.delete_image_tags == ''
+      run: |
+        set -euo pipefail
+        # figure REMOVE_DOCKER_REPO (--remove-docker-repo)
+        if [[ "${{ inputs.include_docker_repo }}" == "true" ]]; then
+          REMOVE_DOCKER_REPO=''
+        elif [[ "${{ inputs.include_docker_repo }}" == "false" ]]; then
+          REMOVE_DOCKER_REPO='--remove-docker-repo'
+        else
+          echo "ERROR: Unsupported input: 'include_docker_repo' (${{ inputs.include_docker_repo }})"
+          exit 1
+        fi
+        for TAG in "${{ inputs.docker_tags }}"; do
+          echo $TAG
+          python3 ${{ github.action_path }}/request_build.py \
+              --docker-tag $TAG \
+              --dest-dir ${{ inputs.dest_dir }} \
+              $REMOVE_DOCKER_REPO
+          # add & commit
+          git add docker_images.txt || true
+          git commit -m "<bot> docker_images.txt: request build ($TAG)" || true
+        done
       shell: bash
 
     - name: Request Removal(s) on CVMFS
