refactor `docker_tags` to `build_images`

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -7,8 +7,11 @@ inputs:
   dest_dir:
     description: 'the CVMFS sub-directory to place/remove images'
     required: true
-  docker_tags:
-    description: 'the list of Docker image tags requested to be built on CVMFS'  # use `${{ needs.docker.outputs.tags }}`
+  build_images:
+    description: |
+      the list of Docker image tags requested to be built on CVMFS'  
+        ex: 'icecube/skymap_scanner:4.0.0', 'ghcr.io/wipacrepo/iceprod:3.0.52', ...
+        hint: use 'needs.docker.outputs.tags' from https://github.com/docker/metadata-action
     default: ''
   delete_image_nametags:
     description: |
@@ -22,9 +25,9 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Set Global Env Vars
+    - name: internal logic (set env vars)
       run: |
-        # step: Set Global Env Vars
+        # step: internal logic (set env vars)
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
         echo "DOCKER_IMAGES_FILE=docker_images.txt" >> "$GITHUB_ENV"
@@ -41,6 +44,10 @@ runs:
           echo "::error::Input Error: 'include_docker_repo' has been deprecated -- rely solely on 'dest_dir'."
           exit 1
         fi
+        if [[ -n "${{ inputs.docker_tags }}" ]]; then
+          echo "::error::Input Error: 'docker_tags' has been deprecated -- use 'build_images'."
+          exit 1
+        fi
         if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
           echo "::error::Input Error: 'delete_image_nametags' has been deprecated -- use 'delete_image_nametags'."
           exit 1
@@ -54,13 +61,13 @@ runs:
         
         # DELETION MODE?
         if [[ -n "${{ inputs.delete_image_nametags }}" ]]; then
-          if [[ -n "${{ inputs.docker_tags }}" ]]; then
-            echo "::error::Input Error: 'delete_image_nametags' forbids 'docker_tags'."
+          if [[ -n "${{ inputs.build_images }}" ]]; then
+            echo "::error::Input Error: 'delete_image_nametags' forbids 'build_images'."
             exit 1
           fi
         # CREATION MODE?
-        elif [[ -z "${{ inputs.docker_tags }}" ]]; then
-          echo "::error::Input Error: 'docker_tags' is required for build mode."
+        elif [[ -z "${{ inputs.build_images }}" ]]; then
+          echo "::error::Input Error: 'build_images' is required for build mode."
           exit 1
         fi
 
@@ -91,7 +98,7 @@ runs:
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
         # update and commit for each tag
-        for IMAGE in "${{ inputs.docker_tags }}"; do
+        for IMAGE in "${{ inputs.build_images }}"; do
           echo "$IMAGE"
           echo "##[group]updating $DOCKER_IMAGES_FILE"
           python3 ${{ github.action_path }}/request_build.py \
