Remove `include_docker_repo` [major] (#8)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -9,31 +9,52 @@ inputs:
     required: true
   docker_tags:
     description: 'the list of Docker image tags requested to be built on CVMFS'  # use `${{ needs.docker.outputs.tags }}`
-    type: string
     default: ''
-  include_docker_repo:
-    description: 'whether to include the docker repo when inserting into CVMFS dir; e.g. icecube/skymap_scanner:3 -> DEST_DIR/skymap_scanner:3 OR DEST_DIR/icecube/skymap_scanner:3'
-    type: boolean  # the incoming type is boolean, but to access it's a string; e.i. 'true', 'false'
-    default: 'true'
   delete_image_tags:
-    description: 'DELETION MODE: Image tag to match (full tag or prefix for SHA matching)'
+    description: |
+      DELETION MODE: Newline-delimited image tags to remove (as literal names or known patterns).
+      Example:
+        delete_image_tags: |
+          v1.2.3
+          main-[SHA]
     default: ''
 
 runs:
   using: "composite"
   steps:
+    - name: Set Global Env Vars
+      run: |
+        # step: Set Global Env Vars
+        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+        
+        echo "DOCKER_IMAGES_FILE=./docker_images.txt" >> "$GITHUB_ENV"
+
+      shell: bash
+
     - name: Check Inputs
       run: |
         # step: Check Inputs
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
-        # DELETION MODE
+        # UNSUPPORTED INPUT
+        if [[ -n "${{ inputs.include_docker_repo }}" ]]; then
+          echo "::error::Input Error: 'include_docker_repo' has been deprecated -- rely solely on 'dest_dir'."
+          exit 1
+        fi
+        
+        # REQUIRED INPUT
+        if [[ -z "${{ inputs.dest_dir }}" ]]; then
+          echo "::error::Input Error: 'dest_dir' is required."
+          exit 1
+        fi
+        
+        # DELETION MODE?
         if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
-          if [[ -z "${{ inputs.dest_dir }}" || -n "${{ inputs.docker_tags }}" ]]; then
-            echo "::error::Input Error: 'delete_image_tags' requires 'dest_dir' and forbids 'docker_tags'."
+          if [[ -n "${{ inputs.docker_tags }}" ]]; then
+            echo "::error::Input Error: 'delete_image_tags' forbids 'docker_tags'."
             exit 1
           fi
-        # CREATION MODE
+        # CREATION MODE?
         elif [[ -z "${{ inputs.docker_tags }}" ]]; then
           echo "::error::Input Error: 'docker_tags' is required for build mode."
           exit 1
@@ -65,25 +86,16 @@ runs:
         # step: Request Build(s) on CVMFS
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
-        # figure REMOVE_DOCKER_REPO (--remove-docker-repo)
-        if [[ "${{ inputs.include_docker_repo }}" == "true" ]]; then
-          REMOVE_DOCKER_REPO=''
-        elif [[ "${{ inputs.include_docker_repo }}" == "false" ]]; then
-          REMOVE_DOCKER_REPO='--remove-docker-repo'
-        else
-          echo "ERROR: Unsupported input: 'include_docker_repo' (${{ inputs.include_docker_repo }})"
-          exit 1
-        fi
-        
         # update and commit for each tag
-        for TAG in "${{ inputs.docker_tags }}"; do
-          echo $TAG
+        for IMAGE in "${{ inputs.docker_tags }}"; do
+          echo "$IMAGE"
+          echo "##[group]updating $DOCKER_IMAGES_FILE"
           python3 ${{ github.action_path }}/request_build.py \
-              --docker-tag $TAG \
-              --dest-dir ${{ inputs.dest_dir }} \
-              $REMOVE_DOCKER_REPO
-          git add docker_images.txt || true
-          git commit -m "<bot> build: $TAG" || true
+              --image-uri "$IMAGE" \
+              --dest-dir ${{ inputs.dest_dir }}
+          echo "##[endgroup]"
+          git add "$DOCKER_IMAGES_FILE" || true
+          git commit -m "<bot> build: $IMAGE" || true
         done
 
       shell: bash
@@ -94,12 +106,29 @@ runs:
         # step: Request Removal(s) on CVMFS
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
-        python3 ${{ github.action_path }}/request_removal.py \
-            --dest-dir "${{ inputs.dest_dir }}" \
-            --delete-image-tags "${{ inputs.delete_image_tags }}"
+        # load into array (w/ trimming)
+        mapfile -t DELETE_IMAGES < <(printf '%s\n' "${{ inputs.delete_image_tags }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
         
-        git add docker_images.txt || true
-        git commit -m "<bot> remove: ${{ inputs.delete_image_tags }}" || true
+        # request all matches for each tag (pattern)
+        for IMAGE in "${DELETE_IMAGES[@]}"; do
+          echo "$IMAGE"
+          echo "##[group]updating $DOCKER_IMAGES_FILE"
+          python3 ${{ github.action_path }}/request_removal.py \
+            --dest-dir "${{ inputs.dest_dir }}" \
+            --image-nametag-pattern "$IMAGE"
+          echo "##[endgroup]"
+          git add "$DOCKER_IMAGES_FILE" || true
+          git commit -m "<bot> remove: $IMAGE" || true
+        done
+
+      shell: bash
+
+    - name: View changes
+      run: |
+        # step: View changes
+        set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
+        
+        git diff --unified=0 origin/main...HEAD
 
       shell: bash
 
