refactor `delete_image_tags` to `delete_image_nametags`

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -10,13 +10,13 @@ inputs:
   docker_tags:
     description: 'the list of Docker image tags requested to be built on CVMFS'  # use `${{ needs.docker.outputs.tags }}`
     default: ''
-  delete_image_tags:
+  delete_image_nametags:
     description: |
-      DELETION MODE: Newline-delimited image tags to remove (as literal names or known patterns).
+      DELETION MODE: Newline-delimited images (name + tag) to remove, indicated verbatim or using known patterns.
       Example:
-        delete_image_tags: |
-          v1.2.3
-          main-[SHA]
+        delete_image_nametags: |
+          foo:v1.2.3
+          foo:main-[SHA]
     default: ''
 
 runs:
@@ -41,6 +41,10 @@ runs:
           echo "::error::Input Error: 'include_docker_repo' has been deprecated -- rely solely on 'dest_dir'."
           exit 1
         fi
+        if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
+          echo "::error::Input Error: 'delete_image_nametags' has been deprecated -- use 'delete_image_nametags'."
+          exit 1
+        fi
         
         # REQUIRED INPUT
         if [[ -z "${{ inputs.dest_dir }}" ]]; then
@@ -49,9 +53,9 @@ runs:
         fi
         
         # DELETION MODE?
-        if [[ -n "${{ inputs.delete_image_tags }}" ]]; then
+        if [[ -n "${{ inputs.delete_image_nametags }}" ]]; then
           if [[ -n "${{ inputs.docker_tags }}" ]]; then
-            echo "::error::Input Error: 'delete_image_tags' forbids 'docker_tags'."
+            echo "::error::Input Error: 'delete_image_nametags' forbids 'docker_tags'."
             exit 1
           fi
         # CREATION MODE?
@@ -81,7 +85,7 @@ runs:
       shell: bash
 
     - name: Request Build(s) on CVMFS
-      if: inputs.delete_image_tags == ''
+      if: inputs.delete_image_nametags == ''
       run: |
         # step: Request Build(s) on CVMFS
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
@@ -101,13 +105,13 @@ runs:
       shell: bash
 
     - name: Request Removal(s) on CVMFS
-      if: inputs.delete_image_tags != ''
+      if: inputs.delete_image_nametags != ''
       run: |
         # step: Request Removal(s) on CVMFS
         set -euo pipefail; echo "now: $(date -u +"%Y-%m-%dT%H:%M:%S.%3N")"
         
         # load into array (w/ trimming)
-        mapfile -t DELETE_IMAGES < <(printf '%s\n' "${{ inputs.delete_image_tags }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
+        mapfile -t DELETE_IMAGES < <(printf '%s\n' "${{ inputs.delete_image_nametags }}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e '/^$/d')
         
         # request all matches for each tag (pattern)
         for IMAGE in "${DELETE_IMAGES[@]}"; do
